name: example-workflow1
run-name: Example Workflow1

# Run on every push

on: [push]

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: step1
        uses: actions/checkout@main
      - name: step2
        run: |
          ls -la
          pwd
        
  job1:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
    - name: My First Step
      run: |
        ls -la
        pwd
        echo "My First step is being executed"
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: My second step
      uses:  py-actions/py-dependency-install@v4
      with:
        path: requirements.txt
    - name: My third step
      run: |
        ls -la
        pwd
        echo "My last step in this job"
      
  job2:
    name: My second job
    needs: job1
    runs-on: windows-latest
    steps:
    - name: My second step
      run: |
        dir
        pwd
        echo "My second step is being executed on Windows"

        
