on:
  push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: My First Step
      run: |
        ls -la
        echo "ORGANISATION VARIABLES:OVAR1=${{ vars.OVAR1 }}"
        echo "ORGANISATION VARIABLES:OVAR2=${{ vars.OVAR2 }}"
        echo "REPOSITORY VARIABLES:RVAR1=${{ vars.RVAR1 }}"
        echo "REPOSITORY VARIABLES:RVAR2=${{ vars.RVAR2 }}"
        echo "REPOSITORY VARIABLES:RVAR3=${{ vars.RVAR3 }}"
        
        echo "ENVIRONMNET QA VARIABLES:RVAR3=${{ vars.env1 }}"
