name: example-workflow1
run-name: Example Workflow1

# Run on every push

on: [push]

jobs:
  job1:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
    - name: My First Step
      run: |
        ls -la
        pwd
        echo "My First step is being executed"
    - name: My second step
      uses:  py-actions/py-dependency-install@v4
      with:
        path: ../requirements.txt
      
  job2:
    name: My second job
    runs-on: windows-latest
    steps:
    - name: My second step
      run: |
        dir
        pwd
        echo "My second step is being executed on Windows"

        
